import { useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, Image, Modal, PanResponder, Pressable, ScrollView, Text, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import * as DocumentPicker from 'expo-document-picker';
import { Ionicons } from '@expo/vector-icons';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { confirmMention, deleteFiles, detectFaces, getFiles, getMentions, getPeople, getPreview, renameMention, resolveFaceBatch, uploadFile } from '@/api';
import type { FileItem, Mention, Person } from '@/types';
import { useTheme } from '@/ThemeContext';
import { Button, Field, Header, Loading, Screen, styles } from '@/ui';

const isImage=(type:string)=>type.toLowerCase().startsWith('image/');
function BboxImage({uri,mentions,onSelect}:{uri:string;mentions:Mention[];onSelect:(m:Mention)=>void}){const {colors}=useTheme();const [size,setSize]=useState({w:1,h:1});return <View style={{alignSelf:'center',width:'100%',aspectRatio:size.w/size.h,maxHeight:390,backgroundColor:'#111'}}><Image source={{uri}} resizeMode="contain" style={{width:'100%',height:'100%'}} onLoad={e=>setSize({w:e.nativeEvent.source.width,h:e.nativeEvent.source.height})}/>{mentions.map((m,i)=>{if(!m.bbox||m.bbox.length<4)return null;const [x1,y1,x2,y2]=m.bbox;return <Pressable key={m.id} onPress={()=>onSelect(m)} style={{position:'absolute',left:`${x1/size.w*100}%`,top:`${y1/size.h*100}%`,width:`${(x2-x1)/size.w*100}%`,height:`${(y2-y1)/size.h*100}%`,borderWidth:2,borderColor:i%2? '#F4A340':colors.accent,backgroundColor:'rgba(33,85,229,.16)'}}/>})}</View>}
function Preview({file,onClose}:{file:FileItem;onClose:()=>void}){const {colors}=useTheme();const [preview,setPreview]=useState<{kind:string;content:string}|null>(null);const [mentions,setMentions]=useState<Mention[]>([]);const [selected,setSelected]=useState<Mention|null>(null);const [name,setName]=useState('');const [people,setPeople]=useState<Person[]>([]);const swipe=PanResponder.create({onMoveShouldSetPanResponder:(_,g)=>Math.abs(g.dx)>12&&Math.abs(g.dx)>Math.abs(g.dy),onPanResponderRelease:(_,g)=>{if(g.dx>80)onClose();}});
 useEffect(()=>{Promise.all([getPreview(file.path),getMentions(file.path),getPeople()]).then(async([p,m,e])=>{const resolved=m.some(item=>!item.bbox||item.bbox.length<4)&&m.length>0?await detectFaces(file.path).catch(()=>m):m;setPreview(p);setMentions(resolved);setPeople(e)}).catch(()=>Alert.alert('Błąd','Nie udało się otworzyć pliku.'))},[file.path]);
 const save=async()=>{if(!selected||!name.trim())return;const existing=people.find(p=>p.displayName.toLowerCase()===name.trim().toLowerCase());await (existing?confirmMention(selected.id,existing.id):renameMention(selected.id,name.trim()));setMentions(await getMentions(file.path));setSelected(null);setName('');};
 return <Modal visible animationType="slide" presentationStyle="fullScreen" onRequestClose={onClose}><SafeAreaProvider><Screen><View style={{flex:1}} {...swipe.panHandlers}><Header title={file.name} action={<Pressable onPress={onClose}><Ionicons name="close" size={28} color={colors.ink}/></Pressable>}/><ScrollView contentContainerStyle={{padding:16}}>{!preview?<Loading/>:preview.kind==='image'?<BboxImage uri={preview.content} mentions={mentions} onSelect={m=>{setSelected(m);setName(m.entityDisplayName||m.label)}}/>:<Text style={{color:colors.ink,lineHeight:23}}>{preview.content}</Text>}{mentions.length>0&&<View style={{marginTop:18}}><Text style={{color:colors.ink,fontWeight:'800',fontSize:16,marginBottom:8}}>Osoby na zdjęciu</Text>{mentions.map((m,i)=><Pressable key={m.id} onPress={()=>{setSelected(m);setName(m.entityDisplayName||m.label)}} style={[styles.card,{backgroundColor:colors.raised,borderColor:i%2?'#F4A340':colors.accent}]}><Text style={{color:colors.ink,fontWeight:'700'}}>Osoba {i+1}: {m.entityDisplayName||m.label}</Text><Text style={{color:colors.muted,fontSize:12,marginTop:3}}>{m.visualCues||'Brak dodatkowego opisu'}</Text></Pressable>)}</View>}{selected&&<View style={[styles.card,{backgroundColor:colors.raised,borderColor:colors.accent}]}><Text style={{color:colors.ink,fontWeight:'700',marginBottom:8}}>Podpisz osobę</Text><Field value={name} onChangeText={setName} placeholder="Imię lub nazwa osoby"/><View style={{flexDirection:'row',gap:8}}><Button label="Zapisz" onPress={()=>save().catch(()=>Alert.alert('Błąd','Nie udało się zapisać.'))}/><Button label="Anuluj" secondary onPress={()=>setSelected(null)}/></View></View>}</ScrollView></View></Screen></SafeAreaProvider></Modal>}

export default function FolderDetail(){const {colors}=useTheme();const params=useLocalSearchParams<{id:string;name?:string}>();const qc=useQueryClient();const [preview,setPreview]=useState<FileItem|null>(null);const [tag,setTag]=useState('');const files=useQuery({queryKey:['files',params.id],queryFn:()=>getFiles(params.id)});const upload=useMutation({mutationFn:(asset:{uri:string;name:string;mimeType?:string})=>uploadFile(params.id,asset,tag),onSuccess:()=>qc.invalidateQueries({queryKey:['files',params.id]})});
 const choose=async(kind:'gallery'|'camera'|'files')=>{try{let assets:{uri:string;name:string;mimeType?:string}[]=[];if(kind==='gallery'){const p=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!p.granted)return Alert.alert('Brak dostępu','Zezwól na dostęp do zdjęć w Ustawieniach.');const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,allowsMultipleSelection:true,quality:0.9});if(!r.canceled)assets=r.assets.map(a=>({uri:a.uri,name:a.fileName||`zdjecie-${Date.now()}.jpg`,mimeType:a.mimeType}));}else if(kind==='camera'){const p=await ImagePicker.requestCameraPermissionsAsync();if(!p.granted)return Alert.alert('Brak dostępu','Zezwól na dostęp do aparatu w Ustawieniach.');const r=await ImagePicker.launchCameraAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,quality:0.9});if(!r.canceled)assets=r.assets.map(a=>({uri:a.uri,name:a.fileName||`aparat-${Date.now()}.jpg`,mimeType:a.mimeType}));}else {const r=await DocumentPicker.getDocumentAsync({multiple:true,type:['image/*','application/pdf','text/plain']});if(!r.canceled)assets=r.assets.map(a=>({uri:a.uri,name:a.name,mimeType:a.mimeType}));}for(const a of assets)await upload.mutateAsync(a);if(assets.length)await resolveFaceBatch((await getFiles(params.id)).filter(f=>isImage(f.type)).map(f=>f.path));}catch(e){Alert.alert('Błąd uploadu','Nie udało się dodać pliku.');}};
 const remove=(file:FileItem)=>Alert.alert('Usuń plik',file.name,[{text:'Anuluj',style:'cancel'},{text:'Usuń',style:'destructive',onPress:()=>deleteFiles([file.path]).then(()=>qc.invalidateQueries({queryKey:['files',params.id]}))}]);
 return <Screen><Header title={params.name||'Folder'} action={<Pressable onPress={()=>router.back()}><Ionicons name="chevron-back" size={28} color={colors.ink}/></Pressable>}/><View style={styles.content}><View style={{flexDirection:'row',gap:8,marginBottom:12}}><Button label="Galeria" onPress={()=>choose('gallery')}/><Button label="Aparat" onPress={()=>choose('camera')} secondary/><Button label="Pliki" onPress={()=>choose('files')} secondary/></View><Field value={tag} onChangeText={setTag} placeholder="Opcjonalny tag osoby (np. Anna)"/><Text style={{color:colors.muted,fontSize:12,marginBottom:10}}>Tag zostanie użyty przy nowych zdjęciach.</Text>{files.isLoading?<Loading/>:<FlatList data={files.data} keyExtractor={x=>x.path} contentContainerStyle={{paddingBottom:20}} ListEmptyComponent={<Text style={{color:colors.muted,textAlign:'center',padding:30}}>Pusty folder</Text>} renderItem={({item})=><Pressable onPress={()=>setPreview(item)} style={[styles.card,{backgroundColor:colors.raised,borderColor:colors.border,flexDirection:'row',alignItems:'center'}]}><View style={{width:54,height:54,borderRadius:8,overflow:'hidden',backgroundColor:colors.accentSoft,marginRight:12,alignItems:'center',justifyContent:'center'}}>{isImage(item.type)&&item.url?<Image source={{uri:item.url}} style={{width:'100%',height:'100%'}}/>:<Ionicons name={isImage(item.type)?'image-outline':'document-text-outline'} size={25} color={colors.accent}/>}</View><View style={{flex:1}}><Text numberOfLines={1} style={{color:colors.ink,fontWeight:'700'}}>{item.name}</Text>{item.extractedText&&<Text numberOfLines={2} style={{color:colors.muted,fontSize:12,marginTop:3}}>{item.extractedText}</Text>}</View><Pressable onPress={()=>remove(item)} hitSlop={8}><Ionicons name="trash-outline" color={colors.danger} size={20}/></Pressable></Pressable>}/>}</View>{preview&&<Preview file={preview} onClose={()=>setPreview(null)}/>}</Screen>}
