import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useTheme } from './ThemeContext';
export function Screen({children}:{children:React.ReactNode}){const {colors}=useTheme();return <SafeAreaView edges={['top','bottom','left','right']} style={[styles.screen,{backgroundColor:colors.surface}]}>{children}</SafeAreaView>}
export function Header({title,action}:{title:string;action?:React.ReactNode}){const {colors}=useTheme();return <View style={[styles.header,{borderBottomColor:colors.border}]}><Text style={[styles.title,{color:colors.ink}]}>{title}</Text>{action}</View>}
export function Button({label,onPress,secondary=false,disabled=false}:{label:string;onPress:()=>void;secondary?:boolean;disabled?:boolean}){const {colors}=useTheme();return <Pressable disabled={disabled} onPress={onPress} style={({pressed})=>[styles.button,{backgroundColor:secondary?colors.raised:colors.accent,borderColor:secondary?colors.border:colors.accent,opacity:disabled?.45:pressed?.7:1}]}><Text style={{color:secondary?colors.ink:'#fff',fontWeight:'700'}}>{label}</Text></Pressable>}
export function Field(props:React.ComponentProps<typeof TextInput>){const {colors}=useTheme();return <TextInput {...props} placeholderTextColor={colors.muted} style={[styles.field,{backgroundColor:colors.raised,borderColor:colors.border,color:colors.ink},props.style]}/>}
export function Loading(){const {colors}=useTheme();return <ActivityIndicator color={colors.accent} style={{margin:32}}/>}
export const styles=StyleSheet.create({screen:{flex:1},header:{paddingHorizontal:20,paddingTop:18,paddingBottom:14,borderBottomWidth:1,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{fontSize:27,fontWeight:'800',letterSpacing:-.5},content:{padding:16},card:{borderRadius:12,borderWidth:1,padding:14,marginBottom:10},button:{minHeight:44,paddingHorizontal:16,borderRadius:10,borderWidth:1,alignItems:'center',justifyContent:'center'},field:{borderWidth:1,borderRadius:10,minHeight:46,paddingHorizontal:13,fontSize:16,marginBottom:10}});
